<?php
/**
 * Default Theme Options
 */
$def_options = array
(
    'bd_setting'                            => array
    (
        'responsive'                        => 1,
        'margin_logo_top'                   => '0',
        'margin_logo_right'                 => '0',
        'margin_logo_bottom'                => '0',
        'margin_logo_left'                  => '0',
        'show_header_ads'                   => 0,
        'show_top_nav'                      => 1,
        'show_top_nav_search'               => 1,
        'show_top_nav_socail_links'         => 1,
        'show_top_nav_contactinfo'          => 1,
        'header_ads_img'                    => get_template_directory_uri()."/images/adv728.png",
        'header_ads_img_url'                => '#',
        'header_ads_img_altname'            => 'Alt name',
        'rss_url'                           => '#',
        'social'                            => array
        (
            'facebook'                      => '#',
            'twitter'                       => '#',
            'google_plus'                   => '#',
            'vimeo'                         => '#',
            'soundcloud'                    => '#',
        ),
        'newsticker_title'                  => "Don't Miss",
        'newsticker_display'                => 'lates',
        'newsticker_bumber'                 => '12',
        'breaking_news_in_pic_title'        => "Breaking News",
        'breaking_news_in_pic_display'      => 'lates',
        'breaking_news_in_pic_bumber'       => '12',
        'h_contact_number'                  => 'Call Us 2-100-703-1191',
        'h_contact_email'                   => 'info@yourdomain.com',
        'notify_theme'                      => 1,
        'layout_type'                       => 'layout_boxed',
        'home_type'                         => 'blog',
        'header_style'                      => 'v1',
        'enable_seo'                        => 1,
        'footer_layout'                     => 'col3',
        'footer_copyright'                  => 1,
        'footer_copyright_text'             => "Copyright 2013 Manshet | All Rights Reserved | Powered by <a href='http://wordpress.org'>WordPress</a>  |  <a href='http://themeforest.net/user/bdayh'>Bdayh</a>",
        'date_format'                       => 'F jS, Y',
        'slider_show'                       => 1,
        'slider_excerpt_show'               => 1,
        'slider_speed'                      => '6000',
        'slider_animation'                  => '500',
        'slider_bumber'                     => '5',
        'slider_display'                    => 'lates',
        'post_meta'                         => 1,
        'post_meta_author'                  => 1,
        'post_meta_cats'                    => 1,
        'post_meta_date'                    => 1,
        'post_meta_comments'                => 1,
        'post_meta_views'                   => 1,
        'excerpt_length_blog'               => '42',
        'blog_displays'                     => 'view_post_formats_small',
        'posts_slideshow_number'            => '5',
        'post_tags'                         => 1,
        'post_pagination'                   => 1,
        'social_sharing_box'                => 1,
        'sharing_facebook'                  => 1,
        'sharing_twitter'                   => 1,
        'sharing_google'                    => 1,
        'sharing_linkedin'                  => 1,
        'sharing_reddit'                    => 1,
        'sharing_tumblr'                    => 1,
        'sharing_pinterest'                 => 1,
        'social_displays'                   => 'sharing_box_v1',
        'post_author_box'                   => 1,
        'post_comments_box'                 => 1,
        'post_comments_valid'               => 1,
        'article_related'                   => 1,
        'article_related_numb'              => '4',
        'related_style'                     => 'images',
        'footer_widgets'                    => 1,
        'footer_social'                     => 1,
        'gmap_width'                        => '100%',
        'gmap_height'                       => '415px',
        'background_displays'               => 'bg_pattren',
        'breadcrumbs'                       => 1,
        'cate_rss'                          => 1,
        'category_desc'                     => 1,
    )
);